### ISSUE TITLE
[Feature] Add option to consider Supply and Shift separately

### ISSUE THREAD

**Issue by ghost** [Rietty/AutoMammet#2]
Not sure if I just lack excel knowledge but trying to copy paste the exported values in spreadsheets like [the one posted on reddit](https://old.reddit.com/r/ffxiv/comments/x4lr7o/) will only populate a single column instead of splitting by Supply and Shift.

Having a toggle to split the two values would save me some time and also make the plugin compatible with more sheet designs.

![image](https://user-images.githubusercontent.com/63500907/189980709-efb12f70-2c41-488b-8bec-24a8665f161a.png)

**Comment by ghost** [comment]
Oh an I did try to copy-paste as CSV as explained in the README.md but it didn't work for some reason.

![image](https://user-images.githubusercontent.com/63500907/189981428-49e29486-d050-4185-b377-a35d74040888.png)

**Comment by Rietty** [comment]
1. Regarding the first comment this can def be added in the future iteration, I will split it up into two buttons for Supply and Demand Shift.

2. The second one you do right click the cells and then do paste special. I'm not sure what's wrong with Google Docs/Sheets for you but that is not an issue with the application.

**Comment by Rietty** [comment]
This will be added into next update/commit.

**Comment by Rietty** [comment]
Added in commit: https://github.com/Rietty/AutoMammet/commit/10e276f7f2f57cff198a9fcc9625f09da6df18de
