### ISSUE TITLE
[Question] Plugin for what?

### ISSUE THREAD

**Issue by Nekkowe** [Rietty/AutoMammet#3]
Sorry, the readme doesn't provide a lot of information - what is this a plugin for, exactly?

**Comment by Rietty** [comment]
I thought it was fairly clear, however the point of this plugin is to simply provide an easy way to export the information from the Island Sanctuary's Supply & Demand menu for the workshop. This can then be fed into any spreadsheet, or a program, website, whatever you want to help solve the workshop crafts. Essentially it is a QoL plugin aimed to prevent you from manually editing 50+ items on a website/sheet/somewhere daily.

For example the main spreadsheet going around right now:

![image](https://user-images.githubusercontent.com/35241556/190422850-a4cec98e-d0a1-431c-b65b-b8bc6ec8360a.png)

You can paste into each column.

**Comment by Nekkowe** [comment]
Sorry, I put that badly - what does this plug *into*? Is it for Dalamud or something else? The readme doesn't say.

**Comment by Rietty** [comment]
I will edit that in, but this is a Dalamud/XIVLauncher plugin. It is currently in the testing branch.

**Comment by Nekkowe** [comment]
I see, thank you!
