### ISSUE TITLE
I can export Popularity, Supply, and such but not the actual product names

### ISSUE THREAD

**Issue by rurri** [Rietty/AutoMammet#4]
When copying these into a spreadsheet I am then left with columns only containing the Popularity, Supply, Demand Shift, and Predicted Popularity but with no product names to associate with them.

This means if I sort or do anything with it I have no way to match it back to the product names.

Is there a way to also export the product name column? Or maybe I am misunderstanding how to get the full spreadsheet?

**Comment by Rietty** [comment]
It actually does not export the full product name, as there isn't a real reason to do so. The names of the items are fixed and do not change, unless they add more items in the future. As such it only exports data. What this means is that most spreadsheets that utilize this information have the names of the items hard-coded into them and only need the values I actually do provide, and they work off that. You're welcome to just make a fork and just add the functionality yourself, it shouldn't be that difficult but it's not something in the scope/or needed for a vast majority of people and won't be implemented.
